ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REVIEW_REQUEST';

ALTER TYPE "BookingReminderKind" ADD VALUE IF NOT EXISTS 'REVIEW_REQUEST';
ALTER TYPE "BookingReminderKind" ADD VALUE IF NOT EXISTS 'REVIEW_REMINDER';
